# Generated by Django 5.1.4 on 2025-01-29 21:40

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_rename_grade_rating_rate_alter_rating_product_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='comment',
            unique_together={('author', 'product')},
        ),
    ]
