# Generated by Django 5.1.4 on 2025-01-17 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='image',
            field=models.BinaryField(blank=True, null=True),
        ),
    ]
