# Generated by Django 5.1.4 on 2025-01-17 19:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_rename_image_user_avatar'),
    ]

    operations = [
        migrations.CreateModel(
            name='PasswordChangeConfirmation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=6)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='password_change_confirmation', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
