# Generated by Django 5.1.4 on 2025-01-22 17:48

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_passwordchangeconfirmation'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='address',
            field=models.TextField(blank=True, null=True, verbose_name='Адрес проживания'),
        ),
        migrations.AddField(
            model_name='user',
            name='inn',
            field=models.CharField(blank=True, max_length=12, null=True, validators=[django.core.validators.RegexValidator(code='invalid_inn', message='ИНН должен содержать ровно 12 цифр.', regex='^\\d{12}$')], verbose_name='ИНН'),
        ),
        migrations.AddField(
            model_name='user',
            name='phone_number',
            field=models.CharField(blank=True, max_length=15, null=True, validators=[django.core.validators.RegexValidator(code='invalid_phone_number', message='Номер телефона должен содержать от 10 до 15 цифр, с опциональным "+" в начале.', regex='^\\+?\\d{10,15}$')], verbose_name='Номер телефона'),
        ),
    ]
