# Generated by Django 5.1.4 on 2025-01-22 22:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_user_telegram_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='telegram_id',
        ),
        migrations.DeleteModel(
            name='SMSConfirmation',
        ),
    ]
